headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
publish = "E:\\WD-301\\6AWEB2189\\Midterm\\MidtermBadging\\dist\\community-help-desk\\browser"
publishOrigin = "inline"
commandOrigin = "ui"
base = "E:\\WD-301\\6AWEB2189\\Midterm\\MidtermBadging"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]